# Generated by Django 5.1.4 on 2025-01-02 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=10)),
                ('glucose', models.CharField(max_length=10)),
                ('blood_pressure', models.CharField(max_length=10)),
                ('skin_thickness', models.CharField(max_length=10)),
                ('insulin', models.CharField(max_length=10)),
                ('bmi', models.CharField(max_length=10)),
            ],
        ),
    ]
