# Generated by Django 5.1.4 on 2025-01-02 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_patient_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='blood_pressure',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='bmi',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='glucose',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='insulin',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='skin_thickness',
            field=models.FloatField(),
        ),
    ]
