# Generated by Django 5.1.4 on 2025-01-03 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_alter_patient_age_alter_patient_blood_pressure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='risk_factor',
            field=models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10),
        ),
    ]
